### ISSUE TITLE
MAC  check failed

### ISSUE THREAD

**Issue by mike-t225** [MythicAgents/atlas#9]
I am not sure if I insert the issue in the right place. I have installed latest mythic with HTTP C2 profile and Atlas. When running Atlas I see that it called back, but right after the initial reply I get errors in mythic server:

```
[ERROR] crypto.py: MAC check failed
Traceback (most recent call last):
  File "/Mythic/app/crypto.py", line 52, in decrypt_message
    decrypted = await decrypt_AES256(
  File "/Mythic/app/crypto.py", line 127, in decrypt_AES256
    h.verify(mac)
  File "/usr/local/lib/python3.8/site-packages/Crypto/Hash/HMAC.py", line 165, in verify
    raise ValueError("MAC check failed")
Value Error: MAC check failed
```

so Atlas tries to call back, but the message is not understood, not sure why.

**Comment by its-a-feature** [comment]
Atlas is currently broken and doesn't have a maintainer. I know it currently has issues with the regex it uses to parse out messages from Mythic, so this might be related to the same issue
